### ISSUE TITLE
Brainstorming #1

### ISSUE THREAD

**Issue by FlyingKoala01** [royalmo/itic-copilot#1]
iTIC Support App:

1) Crear opcio a OCW per download TOTAL de cada Qn. 

	Exemple:
		C:\Users\$USER\Desktop\UPC -> {Q1, Q2, ..., Q8}

2) Bullet List de coses obligatories:
	IDE per programar {VSC - Atom - Emacs(no)}
	Material per comprar {Arduino - material util per futur laboratori}
	Software util {per exemple LaTeX }

3) Bullet list de tips i notes per a cada signatura que l'Usuari estigui cursant?

**Comment by royalmo** [comment]
1. Not so useful
2. and 3. will be done in a PDF made by my friend @FlyingKoala01 (you can work in it now :) )

Thanks :)

**Comment by FlyingKoala01** [comment]
Yes Master :trollface:

**Comment by royalmo** [comment]
As the teacher said during the review, we should implement the feature number 1.
