### ISSUE TITLE
Make User Interface

### ISSUE THREAD

**Issue by royalmo** [royalmo/itic-copilot#24]
A small user interface in which you can choose to enable or disable some features.

Also put some links to somewhere and store some settings (username/pwd) etc.

**Comment by royalmo** [comment]
Paint image of the main idea made with @FlyingKoala01

![image](https://user-images.githubusercontent.com/49844173/174139095-06fba1e6-8acc-417c-a538-7bdaed17c712.png)

**Comment by royalmo** [comment]
@FlyingKoala01 I have done a commit on **2022_06_23_create_user_interface** branch. If you switch to that branch, you have a simple hello world html popup. You can start working from there.

![image](https://user-images.githubusercontent.com/49844173/175252274-bb811b9d-1e56-4581-a88e-f9d2f6a801a9.png)

First, though, you need to update you forked repo to be able to checkout that branch.

GLHF!

**Comment by FlyingKoala01** [comment]
In the "About" section for the UI, what exactly should there be?
Example:
-------
About
Credits
Eric Roy
Owner and main developer of the iTIC copilot extension.

Aida Vers
Translator.

Josep Sucarrats
Logo creator.

Isaac Iglesias
Popup UI developer.

Contribute
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec condimentum cursus orci et condimentum.

License
iTIC copilot is licensed under the GNU General Public License v3.0. Permissions of this strong copyleft license are conditioned on making available complete source code of licensed works and modifications, which include larger works using a licensed work, under the same license. Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
-----

Should the credits be more detailed? What exactly should there be written in the License section, I'm not a lawyer :D and in "contribute" do you want to make sure people know the extension is open source and thus they can help out with its development?

**Comment by royalmo** [comment]
The about section is just a small message (with bigger font size if it is too short) telling the author, github repository and liscene (contribuitors will be listed on GitHub main page).

For example, something like:

```
<- Back   ABOUT
==================

iTIC Copilot (Josep's logo)

Made by Eric Roy (link to GH profile)

Liscence

This extension is part of an open
source project, liscenced with the
GNU General Public Liscence V3
(GPL3). See more details of it here (link to liscence file on GH repo).

Privacy note (should we put this for further functionnalities?)

As you can verify with your own eyes (because it's an Open Source project),
we don't do anything with your data. Passwords or other preferences may
be saved by request, but only locally (we don't receive anything from you).

Want to contribute?

You can report bugs, suggestions, or
contribute to the iTIC Copilot extension
by going in the GitHub repository. (Link to GH repo).
```

How do you see it?

Thx <3

**Comment by FlyingKoala01** [comment]
In settings div, add username & psw fields depending on variable checked. also add scrollbar in settings div ( add fixed size and scrollbar if needed)
